<a href="https://colab.research.google.com/gist/jiajiajia45/f6a7c4f6bd3368dace8e269b6429e741/assignment-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


In [ ]:
print(np.version.version)

1.18.5


In [ ]:
!pip install numpy --upgrade

     |████████████████████████████████| 14.5MB 257kB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5


In [ ]:
import numpy as np
print(np.version.version)

1.19.4


# **NAME : Jaweria Arshad**
ROll No : PIAIC152144


Assignment no 1 



Submitted to: ***Sir Qasim Hussain***

In [ ]:
############# 1 converting into arrays ###################
import numpy as np
data1 = (1, 2,4,6,8,0)
arr1 = np.array(data1)
arr1



array([1, 2, 4, 6, 8, 0])

In [ ]:
############ 2  random  data ###########
data1 = np.random.randn(2, 3)
data1


array([[-1.51554907, -0.3979443 , -0.88589401],
       [ 0.57368652, -0.13555798, -1.02037682]])

In [ ]:
############## 3 multiply randomly###########
data2 = data1 * 10
data2


array([[-15.1554907 ,  -3.97944301,  -8.85894006],
       [  5.7368652 ,  -1.35557981, -10.20376823]])

In [ ]:
############  4 adding ###############
data3 = data1 + data2
data3


array([[-16.67103976,  -4.37738731,  -9.74483407],
       [  6.31055172,  -1.49113779, -11.22414505]])

In [ ]:
################ 5 shape ###############
data1.shape
data2.shape
data3.shape


(2, 3)

In [ ]:
################### 6 type ################
data1.dtype


dtype('float64')

In [ ]:
################ 7 zeros##############
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
############### 8 matrice ##############
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
################ 9 empty ###########
np.empty((2,3))
np.empty((2,3,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [ ]:
############## 10 ones ###########
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
############ 11 full ###########
import numpy as np
np.full(2,3)

array([3, 3])

In [ ]:
######### 12  identity ######
import numpy as np
np.eye(3,4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
########### 13  full_like ###########
np.full_like(5,7)

array(7)

In [ ]:
########## 14  complex #########
np.complex(8,16)

(8+16j)

In [ ]:
######### 15 bool ##########
np.bool(56)

True

In [ ]:
########## 16 defining array ########
arr = np.array([[1. , 2. , 3. ],[4. ,5. , 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
########### 17 multiplication ############
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
####### 18 addition ###########
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
############# 19 subtraction #########
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
########### 20 division ###########
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#####21  dividing by constant ##########
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
######### 22 apply DMAS ###########
arr+(arr*arr)

array([[ 2.,  6., 12.],
       [20., 30., 42.]])

In [ ]:
########## 23 inequalities ########
arr3 = arr1 != arr2
arr3

True

In [ ]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
######### 24 slicing #########
r[5:8]

array([5, 6, 7])

In [ ]:
####### 25 slicing with jumps ########
r[2:8:2]


array([2, 4, 6])

In [ ]:
r[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
############ 26 - 2d slicing ############
arr4 = np.array([[1. ,2. ,3. ],[4. ,5. ,6.],[7. ,8. ,9.]])
arr4
arr4[2][1]

8.0

In [ ]:
############## 27 sequence ##############
import numpy as np
seq = [1 ,2 ,3 ,4, 5,0,  9,6 ,7 ,8]
seq[6 :-2]


[9, 6]

In [ ]:
############# 28 chaging number ########
seq[3 : 5] = [4,9]
seq 

[1, 2, 3, 4, 9, 0, 9, 6, 7, 8]

In [ ]:
############ 29 enumerate ###########
li = {'foo', 'boo', 'goo'}
i=0
mapp = {}
for i,v in enumerate(li):
  mapp[v] = i
mapp  

{'boo': 2, 'foo': 0, 'goo': 1}

In [ ]:
############ 30 sorted ##############
sorted([3,6,9,0,6,7,5,4,2,1,2,8,7,9])

[0, 1, 2, 2, 3, 4, 5, 6, 6, 7, 7, 8, 9, 9]

In [ ]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

In [ ]:
############## 31 zipping ##############
l1 = ['foo', 'boo', 'loo']
l2 = ['char', 'par', 'arr']
l3 = zip(l1 , l2) 
l4 = list(l3)
l4

[('foo', 'char'), ('boo', 'par'), ('loo', 'arr')]

In [ ]:
l5 = ['true', 'false']
l6 = list(zip(l4,l5))
l6

[(('foo', 'char'), 'true'), (('boo', 'par'), 'false')]

In [ ]:
########### 32 pitchers ##############
pitchers = [("Nolan", 'Rayan'),("Roger", "Clemens"), ("Schilling", "Curt")]
f_s ,l_s = list(zip(*pitchers))
f_s

('Nolan', 'Roger', 'Schilling')

In [ ]:
l_s

('Rayan', 'Clemens', 'Curt')

In [ ]:
############ 33 reversed ###########
lr = list(reversed(range(10)))
lr

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
############ 34 creating dictionary ll

ll = dict(zip(reversed(range(10)),range(10)))
ll

{0: 9, 1: 8, 2: 7, 3: 6, 4: 5, 5: 4, 6: 3, 7: 2, 8: 1, 9: 0}

In [ ]:
############# 35 set ############
li = set([1, 7, 1, 7 , 6 ,6 ,7 ])
li

{1, 6, 7}

In [ ]:
######### 36 union #############
lg = {1,3,5,6,7,9,4,3,2}
lf = {4,6,7,9,8,4,2,5,8,9,4,2}
lk = lg|lf
lk

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
########## intersection ##########
ls = lg & lf
ls

{2, 4, 5, 6, 7, 9}

In [ ]:
############## 37 copy #########
ly = lg.copy()
ly |= lf
ly

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [ ]:
############ 38 UPPER Case ##############
lis = ["hands","foot","arms","legs", "eyes", "tounge", "nose","ear","human"]

upp = [x.upper() for x in lis ]
upp

['HANDS', 'FOOT', 'ARMS', 'LEGS', 'EYES', 'TOUNGE', 'NOSE', 'EAR', 'HUMAN']

In [ ]:
############  39 difference ##############
lb = lg-lf
lb

{1, 3}

In [ ]:
################ 40 symmetric-difference ############
ls= lg^lf
ls

{1, 3, 8}

In [ ]:
lo = lg&lf
lo

{2, 4, 5, 6, 7, 9}

In [ ]:
########### 41 tuple #############
t = tuple("no strings")
t

('n', 'o', ' ', 's', 't', 'r', 'i', 'n', 'g', 's')

In [ ]:
t[6]

'i'

In [ ]:
######### 42 pop #############
l1 = ["po", "bo", "lo", "fo", "go"]
l1.pop(2)

'lo'

In [ ]:
########## 43 bisect (finding locations )#########
import bisect
c = [1, 2, 3, 4, 5, 6, 7]
bisect.bisect(c,2)

2

In [ ]:
############ 44 insorting ########## 
bisect.insort(c,7)
c

[1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [ ]:
########### 45 Arrays ##############
import numpy as np

points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [ ]:
########## 46 square root ########
import numpy as np
z= np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [ ]:
############# 47 inequality #############
k = z>0
k

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
########## 48 commulative sum ###########
h = k.cumsum(axis=1)
h

array([[   1,    2,    3, ...,  998,  999, 1000],
       [   1,    2,    3, ...,  998,  999, 1000],
       [   1,    2,    3, ...,  998,  999, 1000],
       ...,
       [   1,    2,    3, ...,  998,  999, 1000],
       [   1,    2,    3, ...,  998,  999, 1000],
       [   1,    2,    3, ...,  998,  999, 1000]])

In [ ]:
######### 49 commulative product #####
g = k.cumprod(axis=0)
g

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
########### 50 Mean ###########
m = g.mean(axis=1)
m

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.